# Generated by Django 4.2.16 on 2024-09-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('FoodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food_Type', to='assessment_app.foodfoodtype')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('directions', models.CharField(max_length=200)),
                ('best_suitable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_best_suitable', to='assessment_app.intaketime')),
                ('ingredients', models.ManyToManyField(related_name='receipe_ingredients', to='assessment_app.ingredient')),
            ],
        ),
    ]
